# Generated by Django 5.1.2 on 2024-12-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_date_evenement_date_debut_evenement_date_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='categorie',
            field=models.CharField(choices=[('SPIRITUAL', 'Spiritualité'), ('EDUCATION', 'Éducation'), ('COMMUNITY', 'Communauté'), ('OTHER', 'Autre')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='evenement',
            name='est_recurrent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evenement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='evenements/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
