# Generated by Django 5.1.2 on 2024-12-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_evenement_categorie_evenement_est_recurrent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predications',
            name='orateur',
        ),
        migrations.RemoveField(
            model_name='predications',
            name='video_url',
        ),
        migrations.AddField(
            model_name='predications',
            name='categorie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='predications',
            name='description',
            field=models.TextField(default='pas de description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='predications',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
